version: "3.7"

services:
    app:
        container_name: ecdltd-container
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: ecdltd-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks: 
            - ecdltd-net
    
    # nginx
    nginx:
        container_name: ecdltd-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8891:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - ecdltd-net

networks: 
    ecdltd-net:
        external: true